In [2]:
import jieba
import jieba.analyse
import csv
import sys
import numpy as np
jieba.set_dictionary('dict.txt.big.txt')

In [3]:
#沒用split_mobile
path_m = "C:\\Users\\fan\\Desktop\\webBug\\mobile\\"
corpus = []
mcorpus = []
for i in range(1,101):
    with open(path_m+'m{0}.txt'.format(i),'r', encoding = 'utf8') as mobile:
        content = mobile.read()
        mcorpus.append(content)
        
for line in mcorpus:
    togetherM=" ".join(jieba.cut(line, cut_all=False))
    togetherM = togetherM.strip()
    corpus.append(togetherM)

Building prefix dict from C:\Users\fan\Desktop\webBug\dict.txt.big.txt ...
Loading model from cache C:\Users\fan\AppData\Local\Temp\jieba.u7fa3f1eb88f67958f22ad5a9691de6fe.cache
Loading model cost 1.473 seconds.
Prefix dict has been built succesfully.


In [4]:
from sklearn import feature_extraction
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(corpus)
print(tfidf.shape)
words = vectorizer.get_feature_names()
weight=tfidf.toarray()
# print(weight)
# print(np.where(weight==np.max(weight)))
# np.argsort(weight, axis=0) 
top=[]
#i代表100篇文章，j代表裡面的斷詞
for i in range(len(corpus)):
    #print('----Document %d----'% (i))
    for j in range(len(words)):
        if weight[i][j] > 0.8:
            top.append(words[j])#查看top n的名字是什麼
            print(words[j], weight[i][j])

(100, 9373)
done 0.8802914301378748


In [5]:
ii = np.unravel_index(np.argsort(weight.ravel())[-110:][::-1], weight.shape)
print(ii)
m_top=[]
count=0

for w in range(0,110):
    #看看top n的名字和數字-沒過濾重複
    print(words[ii[1][w]],weight[ii[0][w]][ii[1][w]])
    
    #把top的名字加入儲存的陣列-過濾重複
    try: 
        if count == 60:
            break
        if words[ii[1][w]] not in m_top :
            m_top.append(words[ii[1][w]])
            count=count+1
    except:
        break
    
    with open('mobile60.csv','w',newline='',encoding='utf-8-sig') as m:
        w = csv.writer(m)
        w.writerow(m_top)
print(count)    
print(m_top)

(array([99, 71, 60, 58, 38, 89, 19, 11, 70, 54, 41, 96, 39, 78, 46, 13, 67,
       81, 84, 15, 69, 93, 39, 75, 51, 83, 45, 92, 67, 69, 63, 55, 31, 46,
       82, 63, 52, 54, 20, 42, 77, 83, 34, 69, 42, 76, 45, 40, 73, 88, 31,
       80, 30, 63, 18,  6, 57, 97, 86, 90, 22, 95,  0, 17, 29, 32, 96,  6,
       84, 23, 12, 11, 61, 65, 87, 47, 55,  0, 56, 81, 24, 28,  9, 16, 41,
       32, 45, 17, 88, 53, 94,  9, 64, 23, 17, 80, 88,  1, 59, 59, 82, 80,
       86, 44, 96, 21, 23, 13, 57, 14], dtype=int32), array([1109, 4452, 6274, 9065, 1787, 8412, 9320,  898, 6666,   10, 7226,
          8, 7790, 2247,   14, 8615,   14,  898,   10, 7956, 8340,    8,
       7796, 4065, 1893,   10, 1570, 5602,   10, 5007,   10, 8822,   14,
         11,   10, 2736, 1416,   14,  727,   14, 7880,   14,  898, 3775,
         11, 6202,   14, 1225, 2324, 5301,   11,   10, 9020,   14, 7798,
         14, 2990, 2143,   10, 4254, 1306,    8,   14,  224, 5221,   14,
       2496,   11,   14,   14, 1922,   14,   10, 2928,  7

In [228]:
#沒用split_food
path_f = "C:\\Users\\fan\\Desktop\\webBug\\food\\"
corpus = []
fcorpus = []
for i in range(1,101):
    with open(path_f+'f{0}.txt'.format(i),'r', encoding = 'utf8') as food:
        content = food.read()
        content = content.strip()
        fcorpus.append(content)
        
for line in fcorpus:
    together=" ".join(jieba.cut(line, cut_all=False))
    together = together.strip()
    corpus.append(together)

In [229]:
from sklearn import feature_extraction
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(corpus)
print(tfidf.shape)
words = vectorizer.get_feature_names()
weight=tfidf.toarray()
# print(weight)
# print(np.where(weight==np.max(weight)))
# np.argsort(weight, axis=0) 
top=[]
#i代表100篇文章，j代表裡面的斷詞
for i in range(len(corpus)):
    #print('----Document %d----'% (i))
    for j in range(len(words)):
        if weight[i][j] > 0.8:
            top.append(words[j])#查看top n的名字是什麼
            print(words[j], weight[i][j])

(100, 10942)
豆花 0.8162842489485129
壽司 0.8651770178649163
壽司 0.8414216532186902


In [230]:
ii = np.unravel_index(np.argsort(weight.ravel())[-80:][::-1], weight.shape)
print(ii)
f_top=[]
count=0

for w in range(0,80):
    #看看top n的名字和數字-沒過濾重複
    print(words[ii[1][w]],weight[ii[0][w]][ii[1][w]])
    
    #把top的名字加入儲存的陣列-過濾重複
    try: 
        if count == 60:
            break
        if words[ii[1][w]] not in f_top :
            f_top.append(words[ii[1][w]])
            count=count+1
    except:
        break
    
    with open('food60.csv','w',newline='',encoding='utf-8-sig') as f:
        w = csv.writer(f)
        w.writerow(f_top)
print(count)    
print(f_top)

(array([74, 92, 15, 70, 28, 19,  2, 13, 58, 93, 73, 55, 26, 26, 10, 24, 35,
       88, 87, 87, 96, 45, 84, 26,  1, 95, 42, 59, 63, 40, 40, 64, 32, 41,
       52, 89, 22, 22, 91, 43,  9, 20, 52, 34, 34,  8,  8, 56, 85, 86, 63,
       77, 90, 47, 59, 41, 55,  6, 80, 34, 54, 50, 53, 53, 17, 96,  1, 60,
       49,  2, 18, 34, 61, 62,  4, 33, 83, 38, 97, 13], dtype=int32), array([ 4118,  4118,  9346,  7414,  4118,  7201, 10650, 10791,  6388,
        6869,  9346,  9379,  1040,  1377,  7395, 10739,  7074,  7347,
        1086,  1095, 10455,  1387,  6771,  1065,  9346,  3726,  2253,
        7395, 10347,  3793,  4476, 10137,  4118, 10784,  1008,  1317,
        1368,   940,  4658, 10246,    55,   870,  1154,  1278,  1373,
        5399,  2720,  7395,  6869, 10739,  6428,  1446,  7154,  8718,
        9451,  6673,  5125,    23,  5982,  8992,  8997,  8933,  1145,
        1192,  1146, 10669,  1876, 10749,  3098,  7197,  7074,  3043,
        4635,    19,  1376,  9141,  7099,  2972,  7166,  6870],
     

In [24]:
print(type(tfidf))
print(type(weight))

<class 'scipy.sparse.csr.csr_matrix'>
<class 'numpy.ndarray'>


In [195]:
#numpy找出最大值和位置
x=np.where(weight==np.max(weight))
print(x)
print(words[4118],weight[74][4118])

(array([74], dtype=int32), array([4118], dtype=int32))
壽司 0.8651770178649163


In [7]:
print(m_top)

['done', '同步', '晴空', '雙清', 'larsonloreal', '越南', '鬧鐘', 'bwhmj', '殘影', '04', '白邊', '03', '耳塞', 'ping', '08', '通知', '藍芽', '資料夾', '耳道', '切換', 'm9', 'iphone', '感應', '安全', '那條', '05', 'u11', 'hdr', 'andyfresh', '自拍', '備份', '日本', 'f7', 'qday', '平板', '降價', '聊天', 'yurian', 'oled', '印度', 'g5', '188', '山寨', 'sense', 'mate', 'xp', 'angela60531', 'joshua781021', '簡訊', '黑卡', '原生', '流量', '視訊', '電池', 'sugar', '皮套', 'kkcity59', '相簿', 'zenui', 'tony12526']
